### ISSUE TITLE
Manifest Not Displaying

### ISSUE THREAD

**Issue by MWhiteFearless** [digirati-co-uk/react-iiif-vault#173]
Hello!

Thanks for building out such a great tool. I'm trying to use it for my project, and for some reason it's not working with my presentation 2 manifest. This same manifest ID works with other IIIF viewers, do you know why it might not be working here? I see that the viewer has worked with other presentation 2 manifests ex. https://gist.githubusercontent.com/stephenwf/988fd0008e886ff278a4c00b8037fe85/raw/487907fd430e2b4e08a20135b230980526367dd6/manifest.json. 

Here's a [sandbox](https://codesandbox.io/p/sandbox/react-iiif-vault-demo-forked-zdwhth?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clteim4tv00063b6hxnpibbur%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clteim4tv00023b6h0ykws8r1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clteim4tv00033b6hxfrtadpx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clteim4tv00053b6hpf15fgl1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clteim4tv00023b6h0ykws8r1%2522%253A%257B%2522id%2522%253A%2522clteim4tv00023b6h0ykws8r1%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clteim4tv00053b6hpf15fgl1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clteim4tv00043b6hmhfgx2wj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clteim4tv00053b6hpf15fgl1%2522%252C%2522activeTabId%2522%253A%2522clteim4tv00043b6hmhfgx2wj%2522%257D%252C%2522clteim4tv00033b6hxfrtadpx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clteim4tv00033b6hxfrtadpx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with the issue. And here's the manifest on it's own https://ids.si.edu/ids/manifest/NMAAHC-2017_36_5_001. Thanks!

**Comment by stephenwf** [comment]
Hi @MWhiteFearless 

I think the issue is the `annotation.on` property. It should point to the canvas or a region of the canvas. The ID seems to point to the Annotation instead.
```
"@id": "https://ids.si.edu/ids/iiif/NMAAHC-2017_36_5_001",
"@type": "oa:Annotation",
...
"on": "https://ids.si.edu/ids/iiif/NMAAHC-2017_36_5_001" <-- Should be Canvas ID.
```

The canvas ID is `https://ids.si.edu/ids/iiif/canvas-NMAAHC-2017_36_5_001` so it should be:
```
"@id": "https://ids.si.edu/ids/iiif/NMAAHC-2017_36_5_001",
"@type": "oa:Annotation",
...
"on": "https://ids.si.edu/ids/iiif/canvas-NMAAHC-2017_36_5_001"
```

I hope that helps! 

Here is the patched manifest, that does load correctly with the `on` value changed
https://gist.githubusercontent.com/stephenwf/c60ed39a0ac3050695fdadc27bb9859d/raw/1aa56fa648b4edc04a1709c813c17d3252455b11/manifest-patched.json

**Comment by MWhiteFearless** [comment]
Thanks for getting back to me! That's really helpful. Unfortunately, my team doesn't own the manifests we're using and so we don't have access to update them. It's good to know what would help though! I'll pass it on. Do you think it would be possible to support the manifest as it is in this project? It works with other viewers so maybe there would be a way to support it here despite the "on" field not being as expected. Really appreciate your help!

**Comment by MWhiteFearless** [comment]
I'm happy to close this issue, I think it would be a nice enhancement to also support this type of manifest on this project since its supported by other large projects like mirador. I've moved forward with our own implementation of openseadragon so I don't need help anymore with this issue!

**Comment by stephenwf** [comment]
Maybe something we can look at later - the viewer relies on the `target`/`on` field quite extensively, so adding workarounds may introduce other bugs. Glad you found another solution! Ideally this would be something that Smithsonian would fix on their end.
