### ISSUE TITLE
Question: Setting the zoom minimum scale to less than 1

### ISSUE THREAD

**Issue by anendlesssupply** [digirati-co-uk/react-iiif-vault#203]
Hi, thanks for all the work that's gone into this library!

Are there any examples of a `CanvasPanel` that allows the zoom to scale below 1? As I understand it the default minimum zoom is 1 as in this [CodeSandbox](https://codesandbox.io/p/sandbox/react-iiif-vault-demo-mcpg98?file=%2Fsrc%2FViewer.tsx%3A3%2C22).

Thanks

**Comment by stephenwf** [comment]
Yes! You can set:
```
const runtimeOptions = { maxOverZoom: 5 };
```

and then pass it into the viewer component: 
```tsx
<CanvasPanel.Viewer runtimeOptions={runtimeOptions} />
```

This will allow you to zoom in further than "100%" into the image. You can also set `maxUnderZoom` to control how small you can make the image, or how far you can zoom out. There is also `visibilityRatio` that will control the minimum percent (0-1) of the image that is visible when you pan to the side of the image. The default is `0.5`.

**Comment by anendlesssupply** [comment]
Thanks, that's perfect :)

I'll close this issue but have one related question: is the initial zoom level configurable?

As a workaround I've been calling `preset.runtime.world.zoomOut()` in a useEffect after the initial render but this triggers an initial zoom transition I'd rather avoid!

**Comment by stephenwf** [comment]
You can pass in `homePosition={{ x, y, width, height }}` to the `Viewer` component. I _think_ these can be negative, so you could do a fixed size if you wanted.

**Comment by anendlesssupply** [comment]
Thanks again, really appreciate the pointer.
